[package]
name = "quest-sys"
version = "0.2.0"
edition = "2024"
links = "QuEST"
description = "Low-level Rust bindings to the QuEST C++ quantum simulation toolkit"
license = "MIT"
repository = "https://github.com/eessmann/quest-rs"
readme = "README.md"
keywords = ["quantum", "simulation", "ffi", "bindings"]
categories = ["external-ffi-bindings", "science"]
build = "build.rs"

[dependencies]
cxx.workspace = true

[build-dependencies]
cxx-build.workspace = true
cmake-package.workspace = true
miette.workspace = true

[dev-dependencies]
approx = "0.5.1"
libc = "0.2.177"

[[example]]
name = "min_example"
path = "examples/min_example.rs"
