use crate::generate::DynError;
use std::{fmt::Write as _, fs, path::Path, process::Command};

pub fn run(source: &Path, check: bool) -> Result<(), DynError> {
	let shards = source.join("src/io/json_reader/src/pennylane_inverse_catalog");
	let root = Path::new(env!("CARGO_MANIFEST_DIR"))
		.parent()
		.and_then(Path::parent)
		.ok_or("workspace directory")?;
	let destination = root.join("crates/quest-qsvt-io/data/inverse");
	if !check {
		fs::create_dir_all(&destination)?;
	}
	let revision = Command::new("git")
		.args(["rev-parse", "HEAD"])
		.current_dir(source)
		.output()?;
	if !revision.status.success() {
		return Err("cannot record C++ catalog revision".into());
	}
	let revision = String::from_utf8(revision.stdout)?;
	let revision = revision.trim();
	if revision.len() != 40 || !revision.chars().all(|value| value.is_ascii_hexdigit()) {
		return Err("unexpected source git revision".into());
	}
	let mut generated = format!(
		"// Generated by xtask generate-qsvt-catalog.\n// Little-endian binary64 coefficient payloads from the pinned C++ catalog.\npub const SOURCE_REVISION: &str = \"{revision}\";\npub static FAMILIES: &[super::CatalogFamily] = &[\n"
	);
	for kappa in [5_u32, 50, 100, 250, 500, 1000, 1500] {
		for (label, epsilon) in [("0p001", 0.001), ("0p01", 0.01), ("0p1", 0.1)] {
			let name = format!("coeffs_kappa_{kappa}_eps_{label}");
			let raw = fs::read_to_string(shards.join(format!("{name}.cpp")))?;
			let values = parse_shard(&raw)?;
			let degree = values.len().checked_sub(1).ok_or("empty catalog family")?;
			if degree > 8105
				|| degree % 2 != 1
				|| values.iter().step_by(2).any(|&value| value != 0.0)
			{
				return Err(format!("invalid degree/parity in {name}").into());
			}
			let bytes: Vec<u8> = values
				.iter()
				.flat_map(|value| value.to_le_bytes())
				.collect();
			publish(&destination.join(format!("{name}.bin")), &bytes, check)?;
			writeln!(
				generated,
				"    super::CatalogFamily {{ kappa: {kappa}, epsilon: {epsilon:?}, degree: {degree}, coefficients: include_bytes!(\"../data/inverse/{name}.bin\") }},"
			)?;
		}
	}
	generated.push_str("];\n");
	publish(
		&root.join("crates/quest-qsvt-io/src/catalog_data.rs"),
		generated.as_bytes(),
		check,
	)?;
	eprintln!(
		"{} 21 inverse catalog families (through degree 8105)",
		if check { "Checked" } else { "Generated" }
	);
	Ok(())
}
fn parse_shard(source: &str) -> Result<Vec<f64>, DynError> {
	let (header, tail) = source
		.split_once(" = {")
		.ok_or("missing coefficient initializer")?;
	let body = tail
		.split_once("};")
		.ok_or("unterminated coefficient initializer")?
		.0;
	let count = header
		.rsplit_once("std::array<double,")
		.ok_or("missing coefficient count")?
		.1
		.split_once('>')
		.ok_or("missing array type end")?
		.0
		.trim()
		.parse::<usize>()?;
	let values = body
		.split(',')
		.map(str::trim)
		.filter(|value| !value.is_empty())
		.map(str::parse::<f64>)
		.collect::<Result<Vec<_>, _>>()?;
	if values.len() != count || values.iter().any(|value| !value.is_finite()) {
		return Err("invalid coefficient count or value".into());
	}
	Ok(values)
}
fn publish(path: &Path, bytes: &[u8], check: bool) -> Result<(), DynError> {
	if check {
		if fs::read(path)? != bytes {
			return Err(format!("stale generated catalog: {}", path.display()).into());
		}
	} else {
		fs::write(path, bytes)?;
	}
	Ok(())
}
#[cfg(test)]
mod tests {
	use super::*;
	use googletest::prelude::*;
	#[gtest]
	fn parses_counted_decimal_values_without_changing_bits() -> googletest::Result<()> {
		let values = parse_shard("std::array<double, 2> const data = {0, 0.10000000000000001,};")
			.or_fail()?;
		expect_that!(values.as_slice(), eq([0.0, 0.1].as_slice()));
		expect_true!(parse_shard("std::array<double, 3> const data = {0, 1,};").is_err());
		Ok(())
	}
}
