// Generated by xtask generate-qsvt-catalog.
// Little-endian binary64 coefficient payloads from the pinned C++ catalog.
pub const SOURCE_REVISION: &str = "568725f2bd488a03a4f98cdf92de924f17b2834a";
pub static FAMILIES: &[super::CatalogFamily] = &[
    super::CatalogFamily { kappa: 5, epsilon: 0.001, degree: 31, coefficients: include_bytes!("../data/inverse/coeffs_kappa_5_eps_0p001.bin") },
    super::CatalogFamily { kappa: 5, epsilon: 0.01, degree: 21, coefficients: include_bytes!("../data/inverse/coeffs_kappa_5_eps_0p01.bin") },
    super::CatalogFamily { kappa: 5, epsilon: 0.1, degree: 9, coefficients: include_bytes!("../data/inverse/coeffs_kappa_5_eps_0p1.bin") },
    super::CatalogFamily { kappa: 50, epsilon: 0.001, degree: 311, coefficients: include_bytes!("../data/inverse/coeffs_kappa_50_eps_0p001.bin") },
    super::CatalogFamily { kappa: 50, epsilon: 0.01, degree: 197, coefficients: include_bytes!("../data/inverse/coeffs_kappa_50_eps_0p01.bin") },
    super::CatalogFamily { kappa: 50, epsilon: 0.1, degree: 81, coefficients: include_bytes!("../data/inverse/coeffs_kappa_50_eps_0p1.bin") },
    super::CatalogFamily { kappa: 100, epsilon: 0.001, degree: 629, coefficients: include_bytes!("../data/inverse/coeffs_kappa_100_eps_0p001.bin") },
    super::CatalogFamily { kappa: 100, epsilon: 0.01, degree: 397, coefficients: include_bytes!("../data/inverse/coeffs_kappa_100_eps_0p01.bin") },
    super::CatalogFamily { kappa: 100, epsilon: 0.1, degree: 167, coefficients: include_bytes!("../data/inverse/coeffs_kappa_100_eps_0p1.bin") },
    super::CatalogFamily { kappa: 250, epsilon: 0.001, degree: 1581, coefficients: include_bytes!("../data/inverse/coeffs_kappa_250_eps_0p001.bin") },
    super::CatalogFamily { kappa: 250, epsilon: 0.01, degree: 971, coefficients: include_bytes!("../data/inverse/coeffs_kappa_250_eps_0p01.bin") },
    super::CatalogFamily { kappa: 250, epsilon: 0.1, degree: 403, coefficients: include_bytes!("../data/inverse/coeffs_kappa_250_eps_0p1.bin") },
    super::CatalogFamily { kappa: 500, epsilon: 0.001, degree: 2699, coefficients: include_bytes!("../data/inverse/coeffs_kappa_500_eps_0p001.bin") },
    super::CatalogFamily { kappa: 500, epsilon: 0.01, degree: 1981, coefficients: include_bytes!("../data/inverse/coeffs_kappa_500_eps_0p01.bin") },
    super::CatalogFamily { kappa: 500, epsilon: 0.1, degree: 801, coefficients: include_bytes!("../data/inverse/coeffs_kappa_500_eps_0p1.bin") },
    super::CatalogFamily { kappa: 1000, epsilon: 0.001, degree: 5439, coefficients: include_bytes!("../data/inverse/coeffs_kappa_1000_eps_0p001.bin") },
    super::CatalogFamily { kappa: 1000, epsilon: 0.01, degree: 3883, coefficients: include_bytes!("../data/inverse/coeffs_kappa_1000_eps_0p01.bin") },
    super::CatalogFamily { kappa: 1000, epsilon: 0.1, degree: 1783, coefficients: include_bytes!("../data/inverse/coeffs_kappa_1000_eps_0p1.bin") },
    super::CatalogFamily { kappa: 1500, epsilon: 0.001, degree: 8105, coefficients: include_bytes!("../data/inverse/coeffs_kappa_1500_eps_0p001.bin") },
    super::CatalogFamily { kappa: 1500, epsilon: 0.01, degree: 6101, coefficients: include_bytes!("../data/inverse/coeffs_kappa_1500_eps_0p01.bin") },
    super::CatalogFamily { kappa: 1500, epsilon: 0.1, degree: 2513, coefficients: include_bytes!("../data/inverse/coeffs_kappa_1500_eps_0p1.bin") },
];
