use std::collections::BTreeMap;
use std::env;
use std::fmt::Write as _;
use std::fs::{self, File};
use std::io::Read;
use std::path::{Path, PathBuf};

use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};

use crate::{Result, explicit_prefix, invalid, io, requested_runtime_dirs, runtime_link_args};

fn encode_sha256(bytes: &[u8]) -> Result<String> {
    let mut encoded = String::new();
    for byte in bytes {
        write!(&mut encoded, "{byte:02x}")
            .map_err(|_| invalid("could not encode SHA-256 digest"))?;
    }
    Ok(encoded)
}

/// Exact bytes of one canonical native input, streamed without loading it all.
#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct FileIdentity {
    /// The lookup path, retaining a loader SONAME symlink when present.
    pub path: PathBuf,
    pub canonical_path: PathBuf,
    pub sha256: String,
}

impl FileIdentity {
    /// Read and hash a native input while retaining its canonical identity.
    ///
    /// # Errors
    ///
    /// Returns an error when the path cannot be made absolute, opened, read, or
    /// canonicalized.
    pub fn read(path: &Path) -> Result<Self> {
        let path = crate::absolute(path)?;
        let canonical_path = fs::canonicalize(&path).map_err(|e| io(&path, e))?;
        let mut file = File::open(&path).map_err(|e| io(&path, e))?;
        let mut digest = Sha256::new();
        let mut buffer = vec![0_u8; 1024 * 1024];
        loop {
            let size = file.read(&mut buffer).map_err(|e| io(&path, e))?;
            if size == 0 {
                break;
            }
            let (bytes_read, _) = buffer.split_at(size);
            digest.update(bytes_read);
        }
        Ok(Self {
            path,
            canonical_path,
            sha256: encode_sha256(&digest.finalize())?,
        })
    }

    /// Validate that this input still names the same file with the same bytes.
    ///
    /// # Errors
    ///
    /// Returns an error when the input cannot be read or its identity differs
    /// from the recorded identity.
    pub fn validate(&self) -> Result<()> {
        let current = Self::read(&self.path)?;
        if current.canonical_path != self.canonical_path || current.sha256 != self.sha256 {
            return Err(invalid(format!(
                "native input changed: {}; regenerate QUEST_NATIVE_CONFIG",
                self.path.display()
            )));
        }
        Ok(())
    }
}

/// Canonical configuration shared by the target bridge and final executable.
/// Generated by `cargo run -p xtask -- configure-native OUTPUT.json`.
#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct NativeConfig {
    pub(crate) schema: u32,
    pub target: String,
    pub prefix: PathBuf,
    pub version: String,
    pub features: BTreeMap<String, String>,
    pub compiler: PathBuf,
    pub compiler_id: String,
    pub compiler_version: String,
    pub include_dirs: Vec<PathBuf>,
    /// Subset of `include_dirs` searched after ordinary include directories.
    pub system_include_dirs: Vec<PathBuf>,
    pub compile_definitions: Vec<String>,
    pub compile_options: Vec<String>,
    pub library: PathBuf,
    pub runtime_library_dirs: Vec<PathBuf>,
    pub(crate) requested_runtime_dirs: Vec<PathBuf>,
    pub(crate) link_search_dirs: Vec<PathBuf>,
    pub(crate) link_libraries: Vec<String>,
    pub(crate) link_options: Vec<String>,
    pub inputs: Vec<FileIdentity>,
}

impl NativeConfig {
    /// Load and validate a recorded native configuration for `target`.
    ///
    /// # Errors
    ///
    /// Returns an error when the record cannot be read, decoded, or validated
    /// against its target, compiler environment, native inputs, or `QuEST`
    /// installation.
    pub fn load(path: &Path, target: &str) -> Result<Self> {
        let bytes = fs::read(path).map_err(|e| io(path, e))?;
        let config: Self = serde_json::from_slice(&bytes)?;
        if config.schema != 2 {
            return Err(invalid("unsupported QUEST_NATIVE_CONFIG schema"));
        }
        if config.target != target {
            return Err(invalid(format!(
                "QUEST_NATIVE_CONFIG targets {}, Cargo targets {target}",
                config.target
            )));
        }
        crate::validate_compiler_environment(target, Some(&config.compiler))?;
        if let Some(prefix) = explicit_prefix()?
            && prefix != config.prefix
        {
            return Err(invalid(
                "QUEST_NATIVE_CONFIG and QUEST_ROOT/QUEST_DIR select different installations",
            ));
        }
        if env::var_os("QUEST_RUNTIME_LIBRARY_PATH").is_some()
            && requested_runtime_dirs()? != config.requested_runtime_dirs
        {
            return Err(invalid(
                "QUEST_RUNTIME_LIBRARY_PATH differs from the recorded loader configuration",
            ));
        }
        if config.inputs.is_empty()
            || !config
                .inputs
                .iter()
                .any(|input| input.canonical_path == config.library)
        {
            return Err(invalid("native record does not identify its QuEST library"));
        }
        for input in &config.inputs {
            println!("cargo:rerun-if-changed={}", input.path.display());
            println!("cargo:rerun-if-changed={}", input.canonical_path.display());
            input.validate()?;
        }
        let header = config.prefix.join("include/quest/include/config.h");
        let parsed = crate::parse_header_configuration(
            &fs::read_to_string(&header).map_err(|e| io(&header, e))?,
        )?;
        if parsed.version != config.version || parsed.features != config.features {
            return Err(invalid(
                "recorded QuEST version/features differ from installed config.h",
            ));
        }
        runtime_link_args("linux", &config.runtime_library_dirs)?;
        Ok(config)
    }

    /// Write this native configuration as canonical, newline-terminated JSON.
    ///
    /// # Errors
    ///
    /// Returns an error when serialization or writing fails.
    pub fn write(&self, path: &Path) -> Result<()> {
        let mut bytes = serde_json::to_vec_pretty(self)?;
        bytes.push(b'\n');
        fs::write(path, bytes).map_err(|e| io(path, e))
    }

    /// Emit dependencies after compiling the CXX bridge, so static library
    /// dependencies retain their required order in Cargo's native-link metadata.
    ///
    /// # Errors
    ///
    /// Returns an error when recorded runtime paths cannot be encoded or do not
    /// satisfy the supported loader policy.
    pub fn emit_cargo_link_metadata(&self) -> Result<()> {
        for directory in &self.link_search_dirs {
            println!("cargo:rustc-link-search=native={}", directory.display());
        }
        for library in &self.link_libraries {
            println!("cargo:rustc-link-lib={library}");
        }
        let encoded = env::join_paths(&self.runtime_library_dirs)
            .map_err(|e| invalid(format!("runtime metadata paths: {e}")))?;
        println!(
            "cargo::metadata=runtime_library_paths={}",
            encoded
                .to_str()
                .ok_or_else(|| invalid("runtime paths must be UTF-8"))?
        );
        println!("cargo::metadata=quest_version={}", self.version);
        self.emit_runtime_paths()
    }

    /// Emit final-target runtime linker arguments for the recorded directories.
    ///
    /// # Errors
    ///
    /// Returns an error when a runtime path cannot be represented by the
    /// supported loader policy.
    pub fn emit_runtime_paths(&self) -> Result<()> {
        for option in &self.link_options {
            println!("cargo:rustc-link-arg={option}");
        }
        for option in runtime_link_args("linux", &self.runtime_library_dirs)? {
            println!("cargo:rustc-link-arg={option}");
        }
        Ok(())
    }
}
