[package]
name = "quest-rs"
version = "0.1.0"
edition.workspace = true
description = "Idiomatic Rust interface to the QuEST quantum simulation toolkit"
license.workspace = true
repository.workspace = true
keywords = ["quantum", "simulation"]
categories = ["science", "simulation"]
build = "build.rs"

[lib]
name = "quest"

[dependencies]
quest-sys.workspace = true
cxx.workspace = true
thiserror.workspace = true
quest-circuit = { workspace = true }
num-complex = { workspace = true }
faer = { workspace = true, features = ["std", "linalg"] }
ndarray = { workspace = true, features = ["std"], optional = true }

[dev-dependencies]
googletest.workspace = true
trybuild = { workspace = true }

[lints]
workspace = true

[features]
ndarray = ["dep:ndarray"]

[build-dependencies]
quest-build = { workspace = true }
