[package]
name = "quest-polynomial"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Typed polynomial bases and mathematical function expressions"

[dependencies]
mathcore.workspace = true
thiserror.workspace = true
num-complex.workspace = true
quest-numerics.workspace = true
faer = { workspace = true, default-features = false, features = ["std", "linalg"] }

[dev-dependencies]
allocation-counter.workspace = true
csv.workspace = true
googletest.workspace = true

[lints]
workspace = true
